### PR TITLE
Fix lint errors

### PR DESCRIPTION
**Pull request by kevva**
Not sure why these wasn't catched by Travis.

### CODE REVIEW

**Comment by sindresorhus** [comment]
What rule? I'm not seeing it locally here either. Are you on latest XO?

**Comment by kevva** [comment]
It failed on https://eslint.org/docs/rules/no-constant-condition for me. It's specified here https://github.com/xojs/eslint-config-xo/blob/master/index.js#L23.

**Comment by sindresorhus** [comment]
Yes, but the default for the `checkLoops` rule option is `false`, and we don't set it to `true`.

**Comment by kevva** [comment]
Yup, I was on an older version of XO, so this can be dismissed :). Strange, thought my editor extension was using the version in the project `node_modules`.

**Pull request closed without merging**
